version: '2.3'

services:
    tvm-dev:
        image: tvm-dev:DietCode
        build:
            context: ./dockerfiles
            dockerfile: tvm.Dockerfile
        runtime: nvidia
        environment:
            - PYTHONPATH=/mnt/tvm/python/build/lib.linux-x86_64-3.8/
            - LD_LIBRARY_PATH=/mnt/tvm/build
        volumes:
            - ..:/mnt
        working_dir: /mnt
        privileged: true
