/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

#include "../space_generator.h"
#include "../tune_context.h"

namespace tvm {
namespace meta_schedule {

/*! \brief The class to represent union of design space generators. */
class SpaceGeneratorUnionNode : public SpaceGeneratorNode {
 public:
  /*! \brief The array of space generators, could be recursive. */
  runtime::Array<SpaceGenerator> space_generators;

  /*!
   * \brief Visitor for variables in python.
   * \note required for non-abstract classes.
   */
  void VisitAttrs(tvm::AttrVisitor* v) {}

  /*!
   * \brief Use given TuneContext to initialize the child space generators.
   * \param context The TuneContext object for initialization.
   */
  void InitializeWithTuneContext(const TuneContext& context) override {
    for (const SpaceGenerator& space_gen : space_generators) {
      space_gen->InitializeWithTuneContext(context);
    }
  }

  /*!
   * \brief Collect the design spaces generated by the child space generators.
   * \return The generated design spaces, i.e., traces.
   */
  Array<tir::Trace> Generate(const IRModule& workload) override {
    Array<tir::Trace> result;
    for (const SpaceGenerator& space_gen : space_generators) {
      Array<tir::Trace> partial = space_gen->Generate(workload);
      result.insert(result.end(), partial.begin(), partial.end());
    }
    return result;
  }
  /*! \brief Class name `SpaceGeneratorUnion` */
  static constexpr const char* _type_key = "meta_schedule.SpaceGeneratorUnion";
  TVM_DECLARE_FINAL_OBJECT_INFO(SpaceGeneratorUnionNode, SpaceGeneratorNode);  // Concrete class
};

/*!
 * \brief Managed reference to SpaceGeneratorUnionNode.
 * \sa SpaceGeneratorUnionNode
 */
class SpaceGeneratorUnion : public SpaceGenerator {
 public:
  /*! \brief Constructor function of SpaceGeneratorUnion class. */
  TVM_DLL explicit SpaceGeneratorUnion(runtime::Array<ObjectRef> space_generators) {
    // Make a new SpaceGeneratorUnion object.
    ObjectPtr<SpaceGeneratorUnionNode> n = make_object<SpaceGeneratorUnionNode>();
    // Copt the child space generators.
    for (const ObjectRef& space_gen : space_generators)
      n->space_generators.push_back(Downcast<SpaceGenerator>(space_gen));
    data_ = std::move(n);
  }

  /*! \brief Declare reference relationship. */
  TVM_DEFINE_MUTABLE_NOTNULLABLE_OBJECT_REF_METHODS(SpaceGeneratorUnion, SpaceGenerator,
                                                    SpaceGeneratorUnionNode);
};

/*!
 * \brief Expose the SpaceGeneratorUnion's constructor function as a member function of
 *  SpaceGenerator.
 * \param space_generators Array of the SpaceGenerator objects to be unioned.
 * \return The constructed SpaceGeneratorUnion object but in SpaceGenerator type.
 */
SpaceGenerator SpaceGenerator::SpaceGeneratorUnion(runtime::Array<ObjectRef> space_generators) {
  return meta_schedule::SpaceGeneratorUnion(space_generators);
}

TVM_REGISTER_NODE_TYPE(SpaceGeneratorUnionNode);  // Concrete class
/*! \brief Register SpaceGenerator's `SpaceGeneratorUnion` function to global registry. */
TVM_REGISTER_GLOBAL("meta_schedule.SpaceGeneratorUnion")
    .set_body_typed(SpaceGenerator::SpaceGeneratorUnion);
/*! \brief Register SpaceGeneratorUnion's `Init...` function to global registry. */
TVM_REGISTER_GLOBAL("meta_schedule.SpaceGeneratorUnionInitializeWithTuneContext")
    .set_body_method<SpaceGeneratorUnion>(&SpaceGeneratorUnionNode::InitializeWithTuneContext);
/*! \brief Register SpaceGeneratorUnion's `Generate` function to global registry. */
TVM_REGISTER_GLOBAL("meta_schedule.SpaceGeneratorUnionGenerate")
    .set_body_method<SpaceGeneratorUnion>(&SpaceGeneratorUnionNode::Generate);

}  // namespace meta_schedule
}  // namespace tvm
